---
- name: Install Nginx on remote server
  hosts: remoteserver
  become: True

  vars:
    ansible_user: ruli
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
    
    - name: Install Nginx
      yum:
        name: nginx
        state: present
    - name: Remove existing nginx conf
      file:
        path: /etc/nginx/nginx/nginx.conf
        state: absent

    - name: Copy nginx config
      copy:
        src: ./conf/nginx.conf
        dest: /etc/nginx/nginx.conf
        
    - name: Copy index.html
      template:
        src: ../templates/index.html
        dest: /usr/share/nginx/html/index.html
        mode: 0644
    
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted