---
- name: Install Nginx on remote server
  hosts: remoteserver
  become: true

  vars:
    ansible_user: ruli
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  
- hosts: remoteserver
  become: true
  roles:
    - preparer

- hosts: remoteserver
  become: true
  roles:
    - installer

- hosts: remoteserver
  become: true
  roles:
    - filing

- hosts: remoteserver
  become: true
  roles:
    - restarter
  